language: android
jdk: oraclejdk8

android:
    components:
        - tools
        - tools #Running this twice get's the latest build tools (https://github.com/codepath/android_guides/wiki/Setting-up-Travis-CI)
        - platform-tools
        - android-25
        - build-tools-25.0.3
        - extra

script:
    - ./gradlew build jacocoTestReport

after_success:
    - bash <(curl -s https://codecov.io/bash)
